import Navbar from "@/components/navbar";
import AuthProvider from "@/providers/auth-provider";
import "@/styles/globals.css";

import { Poppins } from "next/font/google";
import { cn } from "@/lib/utils";
const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["400", "600"],
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.0/flowbite.min.css"
          rel="stylesheet"
        />
      </head>
      <body
        className={`bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 font-sans ${poppins.variable}bg-slate-100`}
      >
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.0/flowbite.min.js"></script>
      </body>
    </html>
  );
}
