# Generated by Django 4.2.8 on 2023-12-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='purchases', to='ecommerce.orderrequest'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
