# Generated by Django 4.2.8 on 2023-12-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='shopping_cart', to='ecommerce.orderrequest'),
        ),
    ]
