# Generated by Django 4.2.8 on 2023-12-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_shoppingcart_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(max_length=50),
        ),
    ]
